# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'
inhibit_all_warnings!
use_frameworks!

target 'VIPhotoBrowser_Example' do

  # Pods for VIPhotoBrowser_Example
  pod 'VIPhotoBrowser', :path => '../'
  pod 'Masonry'

end
