# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'
inhibit_all_warnings!
use_frameworks!

target 'GFPhotoBrowser_Example' do

  # Pods for GFPhotoBrowser_Example
  pod 'GFPhotoBrowser', :path => '../'
  pod 'Masonry'

end
