# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

branches:
  only:
    - master
language: objective-c
osx_image: xcode8.1
env:
    matrix:
    - OS='10.1' name='iPhone 6'

# cache: cocoapods
podfile: Example/Podfile
before_install:
# - gem install xcpretty
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --verbose --project-directory=Example
script:
- xcodebuild clean -destination "platform=iOS Simulator,OS=$OS,name=$name" -workspace Example/GFPhotoBrowser.xcworkspace -scheme GFPhotoBrowser-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO
- pod lib lint GFPhotoBrowser.podspec
